site_name: "Cube Wrangler"
site_url: https://network-wrangler.github.io/cube_wrangler
repo_url: https://github.com/network-wrangler/cube_wrangler

use_directory_urls: false

theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.indexes
    - navigation.tabs
    - navigation.expand
    - toc.integrate
    - toc.follow
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: grey
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - autorefs
  - awesome-pages
  - mike
  - mkdocs-jupyter:
      include_source: True
  - mkdocstrings:
      default_handler: python
      enable_inventory: true
      handlers:
        python:
          paths: [.]
          selection:
            new_path_syntax: true
          rendering:
            show_root_heading: true
            show_source: true
            heading_level: 3
#      custom_templates: templates
  - search
  - table-reader

nav:
  - Home: index.md
  - API: api.md

extra:
  version:
    provider: mike
    default: latest

extra_css:
  - https://use.fontawesome.com/releases/v5.13.0/css/all.css

markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - meta
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.smartsymbols
  - smarty
  - toc:
      # insert a blank space before the character
      permalink: " ¶"
