[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cube_wrangler"
version = "0.0.1"
license = {file = "LICENSE.txt"}
readme = "README.md"
dependencies = [
    "pytest",
]
requires-python = "=3.7"

[project.urls]
"Source"  = "https://github.com/i-am-sijia/cube_wrangler"