channels:
  - conda-forge
  - nodefaults
dependencies:
  - affine=2.3.0
  - boost-cpp=1.74.0
  - branca=0.4.2
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2021.10.8
  - cairo=1.16.0
  - certifi=2021.10.8
  - cffi=1.14.6
  - cfitsio=3.470
  - chardet=4.0.0
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cryptography=3.4.8
  - curl=7.79.1
  - cycler=0.10.0
  - decorator=5.1.0
  - expat=2.4.1
  - fiona=1.8.20
  - folium=0.12.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.10.4
  - freexl=1.0.6
  - gdal=3.3.2
  - geopandas=0.10.1
  - geopandas-base=0.10.1
  - geos=3.9.1
  - geotiff=1.7.0
  - gettext=0.19.8.1
  - hdf4=4.2.15
  - hdf5=1.12.1
  - icu=68.1
  - idna=2.10
  - jbig=2.1
  - jinja2=3.0.2
  - joblib=1.1.0
  - jpeg=9d
  - kealib=1.4.14
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - lcms2=2.12
  - lerc=2.2.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.4.2
  - libgdal=3.3.2
  - libglib=2.68.4
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.8.1
  - libpng=1.6.37
  - libpq=13.3
  - librttopo=1.1.0
  - libspatialindex=1.9.3
  - libspatialite=5.0.1
  - libssh2=1.10.0
  - libtiff=4.3.0
  - libwebp-base=1.2.1
  - libxml2=2.9.12
  - libzip=1.8.0
  - libzlib=1.2.11
  - lz4-c=1.9.3
  - mapclassify=2.4.3
  - markupsafe=2.0.1
  - matplotlib-base=3.4.3
  - mkl=2021.3.0
  - munch=2.5.0
  - networkx=2.5
  - numpy=1.21.2
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - pandas=1.3.3
  - pcre=8.45
  - pillow=8.3.2
  - pip=21.3
  - pixman=0.40.0
  - poppler=21.09.0
  - poppler-data=0.4.11
  - postgresql=13.3
  - proj=8.1.1
  - pycparser=2.20
  - pyopenssl=21.0.0
  - pyparsing=2.4.7
  - pyproj=3.2.1
  - pysocks=1.7.1
  - python=3.7.10
  - python-dateutil=2.8.2
  - python_abi=3.7
  - pytz=2021.3
  - rasterio=1.2.10
  - requests=2.25.1
  - rtree=0.9.7
  - scikit-learn=1.0
  - scipy=1.7.1
  - setuptools=58.2.0
  - shapely=1.7.1
  - six=1.16.0
  - snuggs=1.4.7
  - sqlite=3.36.0
  - tbb=2021.3.0
  - threadpoolctl=3.0.0
  - tiledb=2.3.4
  - tk=8.6.11
  - tornado=6.1
  - urllib3=1.26.7
  - wheel=0.37.0
  - xerces-c=3.2.3
  - xyzservices=2021.9.1
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.5.0
  - pip:
    - alabaster==0.7.12
    - anyio==3.3.3
    - argcomplete==1.12.3
    - argon2-cffi==21.1.0
    - atomicwrites==1.4.0
    - attrs==20.3.0
    - babel==2.9.1
    - backcall==0.2.0
    - black==21.9b0
    - bleach==4.1.0
    - cchardet==2.1.7
    - colorama==0.4.4
    - commonmark==0.9.1
    - debugpy==1.5.0
    - defusedxml==0.7.1
    - descartes==1.1.0
    - docutils==0.17.1
    - entrypoints==0.3
    - geographiclib==1.52
    - geojson==2.5.0
    - gitdb==4.0.7
    - gitpython==3.1.24
    - imagesize==1.2.0
    - importlib-metadata==4.8.1
    - importlib-resources==5.2.2
    - iniconfig==1.1.1
    - ipykernel==6.4.1
    - ipython==7.28.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.5
    - isoweek==1.3.3
    - jedi==0.18.0
    - jsonschema==4.1.0
    - jupyter==1.0.0
    - jupyter-client==7.0.6
    - jupyter-console==6.4.0
    - jupyter-core==4.8.1
    - jupyter-server==1.11.1
    - jupyter-server-mathjax==0.2.3
    - jupyterlab-widgets==1.0.2
    - lark-parser==0.12.0
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - mypy-extensions==0.4.3
    - nbconvert==5.6.1
    - nbdime==3.1.0
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - notebook==6.4.4
    - osmnx==0.14.1
    - packaging==21.0
    - pandocfilters==1.5.0
    - parso==0.8.2
    - partridge==1.1.1
    - pathspec==0.9.0
    - pickleshare==0.7.5
    - platformdirs==2.4.0
    - pluggy==1.0.0
    - prometheus-client==0.11.0
    - prompt-toolkit==3.0.20
    - py==1.10.0
    - pygments==2.10.0
    - pyrsistent==0.18.0
    - pytest==6.2.5
    - pytest-notebook==0.6.1
    - traitlets==5.1.0
    - typing-extensions==3.10.0.2
    - unidecode==1.3.2
    - wcwidth==0.2.5
    - zipp==3.6.0
