name: Clean Docs for Deleted References
on:
  delete:

jobs:
  build:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.12"
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      
      - name: Install cube wrangler
        run: |
          uv sync --group doc
        
      - name: Configure Git user
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Delete defunct docs versions
        run: |
          echo "Deleting ${{ github.event.ref_name }} version from docs"
          uv run mike delete --push ${{ github.event.ref_name }}